### ISSUE TITLE
Download link for shanghaitech

### ISSUE THREAD

**Issue by tea1528** [Ling-Bao/ACSCP_cGAN#1]
Hi, I was wondering whether you have any plan to release the dataset through dropbox or google drive. It seems like downloading through Baidu cloud requires an account which also needs Chinese phone number.

Can you please also upload the dataset to any other platforms?

Thanks.

**Comment by RQuispeC** [comment]
Hi, you may be interested in my implementation in pytorch. It includes the density map generation.
https://github.com/RQuispeC/pytorch-ACSCP
